# Welcome to Serverless!
# Please validate online always if you done any changes manually to yml file http://www.yamllint.com/
# Happy Coding!

service: session3-face-alignment


provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  environment:
    # stage: ${opt:stage}
    S3_BUCKET: sridevimodels
    MODEL_PATH: shape_predictor_5_face_landmarks.dat
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::sridevimodels/*

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"
package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  main_handler:
    handler: handler.face_alignment_handler
    memorySize: 3008
    timeout: 60
    events:
      - http:
          path: align
          method: post
          cors: true

plugins:
  - serverless-python-requirements
